ops_shell/urls.py
from django.conf.urls import url, include
from django.contrib import admin

#Webterminal api
from rest_framework import routers
from shell.api import ServerGroupViewSet,ServerInforViewSet,CommandsSequenceViewSet,CredentialViewSet

from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.views.static import serve

#Register webterminal api
router = routers.DefaultRouter()
router.register('servergroup', ServerGroupViewSet)
router.register('serverinfo', ServerInforViewSet)
router.register('commandssequence', CommandsSequenceViewSet)
router.register('credential', CredentialViewSet)

from shell import urls as shell_urls
from account import urls as account_urls

from settings import MEDIA_ROOT

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('shell:index')), name='index'),
    url(r'^shell/', include(shell_urls, namespace='shell')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
]

shell/urls.py
from django.conf.urls import url

from shell.views import IndexView
from shell.views import ServerListView, SshTerminalKill, server_list_js
from shell.views import SshLogList, SshTerminalMonitor, SshLogPlay

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^sshlogslist/$', SshLogList.as_view(), name='sshlogslist'),
    url(r'^sshterminalkill/$',SshTerminalKill.as_view(), name='sshterminalkill'),
    url(r'^sshlogplay/(?P<pk>[0-9]+)/', SshLogPlay.as_view(), name='sshlogplay'),
    url(r'^sshterminalmonitor/(?P<pk>[0-9]+)/', SshTerminalMonitor.as_view(), name='sshterminalmonitor'),
    url(r'^(?P<region>[\w-]+)/(?P<role>[\w-]+)/$', ServerListView.as_view(), name='server_list'),
    url(r'^(?P<region>[\w-]+)/(?P<role>[\w-]+)/js/$', server_list_js, name='server_list_js'),



]

shell/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.exceptions import ValidationError

try:
    import simplejson as json
except ImportError:
    import json
from django.contrib.auth.models import User
import uuid
from django.utils.text import slugify


class ServerInfor(models.Model):
    name = models.CharField(max_length=40, verbose_name='Server name', blank=False, unique=True)
    hostname = models.CharField(max_length=40, verbose_name='Host name', blank=True)
    ip = models.GenericIPAddressField(protocol='ipv4', blank=False)
    createdatetime = models.DateTimeField(auto_now_add=True)
    updatedatetime = models.DateTimeField(auto_created=True, auto_now=True)
    credential = models.ForeignKey('Credential')

    def __unicode__(self):
        return self.name

    def gethostname(self):
        return slugify(self.hostname)


class ServerGroup(models.Model):
    name = models.CharField(max_length=40, verbose_name='Server group name', blank=False, unique=True)
    servers = models.ManyToManyField(ServerInfor, related_name='servers')
    createdatetime = models.DateTimeField(auto_now_add=True)
    updatedatetime = models.DateTimeField(auto_created=True, auto_now=True)

    def __unicode__(self):
        return self.name


class Credential(models.Model):
    name = models.CharField(max_length=40, verbose_name='Credential name', blank=False, unique=True)
    username = models.CharField(max_length=40, verbose_name='Auth user name', blank=False)
    port = models.PositiveIntegerField(default=22, blank=False)
    method = models.CharField(max_length=40, choices=(('password', 'password'), ('key', 'key')), blank=False)
    key = models.TextField(blank=True)
    password = models.CharField(max_length=40, blank=True)
    proxy = models.BooleanField(default=False)
    proxyserverip = models.GenericIPAddressField(protocol='ipv4', null=True, blank=True)
    proxyport = models.PositiveIntegerField(blank=True, null=True)
    proxypassword = models.CharField(max_length=40, verbose_name='Proxy password', blank=True)

    def __unicode__(self):
        return self.name

    def clean(self):
        if self.method == 'password' and len(self.password) == 0:
            raise ValidationError('If you choose password auth method,You must set password!')
        if self.method == 'password' and len(self.key) > 0:
            raise ValidationError('If you choose password auth method,You must make key field for blank!')
        if self.method == 'key' and len(self.key) == 0:
            raise ValidationError('If you choose key auth method,You must fill in key field!')
        if self.method == 'key' and len(self.password) > 0:
            raise ValidationError('If you choose key auth method,You must make password field for blank!')
        if self.proxy:
            if self.proxyserverip is None or self.proxyport is None:
                raise ValidationError('If you choose auth proxy,You must fill in proxyserverip and proxyport field !')


class CommandsSequence(models.Model):
    name = models.CharField(max_length=40, verbose_name='Task name', blank=False, unique=True)
    commands = models.TextField(verbose_name='Task commands', blank=False)
    group = models.ManyToManyField(ServerGroup, verbose_name='Server group you want to execute')

    def __unicode__(self):
        return self.name

    def clean(self):
        try:
            json.dumps(self.commands)
        except Exception:
            raise ValidationError('Commands sequence is not valid json type')

    def save(self, *args, **kwargs):
        if isinstance(self.commands, (list)):
            self.commands = json.dumps(self.commands)
        super(CommandsSequence, self).save(*args, **kwargs)


class SshLog(models.Model):
    hostname = models.CharField(max_length=64, blank=True, null=True)
    ip = models.GenericIPAddressField(protocol='ipv4', blank=False)
    channel = models.CharField(max_length=100, verbose_name='Channel name', blank=False, unique=True, editable=False)
    log = models.UUIDField(max_length=100, default=uuid.uuid4, verbose_name='Log name', blank=False, unique=True,
                           editable=False)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(auto_created=True, auto_now=True)
    is_finished = models.BooleanField(default=False)
    user = models.ForeignKey(User)
    width = models.PositiveIntegerField(default=90)
    height = models.PositiveIntegerField(default=40)

    def __unicode__(self):
        return self.ip


class Region(models.Model):
    name = models.CharField(max_length=32)
    short_name = models.CharField(max_length=8)
    aws_name = models.CharField(max_length=32)

    def __unicode__(self):
        return self.name


class Role(models.Model):
    name = models.CharField(max_length=64)
    region = models.ManyToManyField(Region, related_name='roles')

    def __unicode__(self):
        return self.name

shell/views.py
# -*- coding: utf-8 -*-
import itertools
from operator import itemgetter

from django.views.generic import TemplateView, ListView

from django.http import JsonResponse
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView,CreateView
from django.views.generic.detail import DetailView
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from opslib_boto3.ec2 import EC2Instance
from opslib_boto3.base import regions_get, env_get

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required

import json
from django.utils.timezone import now
from shell.models import SshLog
from shell.interactive import get_redis_instance
from django.conf import settings

REGIONS = regions_get()

# Create your views here.


class LoginRequiredMixin(object):

    @classmethod
    def as_view(cls):
        return login_required(super(LoginRequiredMixin, cls).as_view())

def ec2_list_instances(region, role, version=None, build=None, state=None, env='ops'):
    ec2 = EC2Instance(region=region, env=env)

    instances = ec2.instance_list(role=role, version=version, build=build, state=state)

    select_instances = []
    for instance in instances:
        tags = instance.get('Tags', [])
        id = instance.get('InstanceId', '')
        type = instance.get('InstanceType')
        tag_name = [tag.get('Value') for tag in tags if tag.get('Key') == 'Name'][0]
        tag_version = None
        name_list = tag_name.split('-')
        for value in name_list:
            if value == '20':
                tag_version = '20'
                break
            if value == '30':
                tag_version = '30'
                break

        public_ip = instance.get('PublicIpAddress', None)
        private_ip = instance.get('PrivateIpAddress', None)
        key_pair = instance.get('KeyName', '')
        state = instance.get('State', {}).get('Name', '')

        select_instances.append({
            'name': tag_name,
            'id': id,
            'tag_version': tag_version,
            'public_ip': public_ip,
            'private_ip': private_ip,
            'key_pair': key_pair,
            'state' : state
        })

    return select_instances


class SshTerminalKill(LoginRequiredMixin, View):
    login_required = True

    def post(self, request):
        if request.is_ajax():
            channel_name = request.POST.get('channel_name', None)
            try:
                data = SshLog.objects.get(channel=channel_name)
                if data.is_finished:
                    return JsonResponse({'status': False, 'message': 'Ssh terminal does not exist!'})
                else:
                    data.end_time = now()
                    data.is_finished = True
                    data.save()

                    queue = get_redis_instance()
                    redis_channel = queue.pubsub()
                    queue.publish(channel_name, json.dumps(['close']))

                    return JsonResponse({'status': True, 'message': 'Terminal has been killed !'})
            except ObjectDoesNotExist:
                return JsonResponse({'status': False, 'message': 'Request object does not exist!'})


class IndexView(LoginRequiredMixin, TemplateView):
    login_required = True
    template_name = 'base.html'


class ServerListView(LoginRequiredMixin, ListView):
    queryset = []
    login_required = True
    template_name = 'shell/server_list.html'

    def get_context_data(self, **kwargs):
        context = super(ServerListView, self).get_context_data(**kwargs)
        regions_re = dict((value, key) for key, value in REGIONS.items())
        region = self.kwargs['region']
        role = self.kwargs['role']
        context['region'] = regions_re[region]
        context['role'] = role

        return context


class SshLogList(LoginRequiredMixin, ListView):
    model = SshLog
    template_name = 'shell/logs.html'
    ordering = ['-start_time']


class SshTerminalMonitor(LoginRequiredMixin, DetailView):
    model = SshLog
    template_name = 'shell/shellmonitor.html'


class SshLogPlay(LoginRequiredMixin, DetailView):
    model = SshLog
    template_name = 'shell/logreplay.html'

    def get_context_data(self, **kwargs):
        context = super(SshLogPlay, self).get_context_data(**kwargs)
        objects = kwargs['object']
        context['logpath'] = '{0}{1}-{2}-{3}/{4}.json'.format(settings.MEDIA_URL, objects.start_time.year,
                                                              objects.start_time.month, objects.start_time.day,
                                                              objects.log)
        return context


def show_text(intance):
    if intance['state'] == 'running':
        if intance['public_ip']:
            return '<font color="green">' + intance['public_ip'] + '</font>'
        else:
            return '<font color="green">' + intance['private_ip'] + '</font>'

    elif intance['state'] == 'stopping':
        return '<font color="red">' + intance['id'] + '</font>'
    elif intance['state'] == 'stopped':
        return '<font color="red">' + intance['id'] + '</font>'
    elif intance['state'] == 'pending':
        return '<font color="#F5B041">' + intance['id'] + '</font>'


def state_icon(state):
    if state == 'running':
        return 'fa fa-play'
    elif state == 'stopping':
        return 'fa fa-pause'
    elif state == 'stopped':
        return 'fa fa-stop'
    elif state == 'pending':
        return 'fa fa-gears'


def server_list_js(request, region, role):
    select_instances = ec2_list_instances(region=region, role=role)
    prod_select_instances = ec2_list_instances(region=region, role=role, env='pro')

    select_instances = sorted(select_instances, key=lambda k: k['name'])
    prod_select_instances = sorted(prod_select_instances, key=lambda k: k['name'])

    re_data = [{'data': 'Staging', 'text': 'Staging', 'state': {'opened': True}, 'children': []},
               {'data': 'Product', 'text': 'Product', 'state': {'opened': True}, 'children': []}]

    for key, value in itertools.groupby(select_instances, key=itemgetter('name')):
        re_data[0]['children'].append({'data': key, 'text': key, 'state': {'opened': True}, 'children':
            [{'data': instance['public_ip'],
              'icon': state_icon(instance['state']),
              'text': show_text(instance),
              'key_pair': instance['key_pair'],
              'ip': instance['public_ip'],
              'hostname': instance['name']}
             for instance in value]})

    for key, value in itertools.groupby(prod_select_instances, key=itemgetter('name')):
        re_data[1]['children'].append({'data': key, 'text': key, 'state': {'opened': True}, 'children':
            [{'data': instance['public_ip'],
              'icon': state_icon(instance['state']),
              'text': show_text(instance),
              'key_pair': instance['key_pair'],
              'ip': instance['public_ip'],
              'hostname': instance['name']}
             for instance in value]})

    re_data[0]['children'][0]['children'].append({
        'data': 'fa fa-play',
        'icon': 'fa fa-play',
        'text': '118.25.11.18',
        'key_pair': 'ali',
        'ip': '118.25.11.18',
        'hostname': 'aliyun'
    })


    return JsonResponse(re_data, safe=False)

shell/templates/shell/logreplay.html
{% load staticfiles %}

<html>
<head>
    <style>
      body { background-color: #666; }
    </style>
  <link rel="stylesheet" type="text/css" href="{% static 'js/asciinema/asciinema-player.css' %}" />
</head>
<body>
  <asciinema-player src="{{logpath}}"></asciinema-player>

  <script src="{% static 'js/asciinema/asciinema-player.js' %}"></script>
</body>
</html>

shell/templates/shell/logs.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static "js/toastr/toastr.css" %}">
  <link href="{% static "js/advanced-datatable/css/demo_page.css" %}" rel="stylesheet" />
  <link href="{% static "js/advanced-datatable/css/demo_table.css" %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static "js/data-tables/DT_bootstrap.css" %}" />
    <link rel="stylesheet" href="{% static "js/json-view/jquery.jsonview.min.css" %}">
<link rel="stylesheet" href="{% static "js/bootstrap-dialog/css/bootstrap-dialog.css" %}">
{% endblock %}

{% block page-body %}
    <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <header class="panel-heading">
                    Dynamic Table
                </header>
                <div class="panel-body">
                    <div class="adv-table">
                        <table  class="display table table-bordered table-striped" id="dynamic-table">
                            <thead>
                                <tr>
                                    <th class="hidden-phone">User</th>
                                    <th class="hidden-phone">Hostname</th>
                                    <th class="hidden-phone">IP</th>
                                    <th class="hidden-phone">Start Time</th>
                                    <th class="hidden-phone">End Time</th>
{#                                    <th class="hidden-phone">is finished</th>#}
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for object in object_list %}
                                    <tr>
                                        <td>{{ object.user.username }}</td>
                                        <td>{{ object.hostname }}</td>
                                        <td>{{ object.ip }}</td>
                                        <td>{{ object.start_time|date:'Y-m-d H:i:s'}}</td>
                                        <td>{{ object.end_time|date:'Y-m-d H:i:s'}}</td>
                                        <td>
                                            {% if object.is_finished %}
                                                <button class="btn btn-xs btn-success" type="button" onclick="play('{{object.user.username}}','{{object.ip}}','{{object.start_time}}','{{object.start_time}}','{% url 'shell:sshlogplay' object.id %}');">Replay</button>
                                            {% else %}
                                                <button class="btn btn-xs btn-info" type="button" onclick="monitor('{{object.user.username}}','{{object.ip}}','{{object.start_time}}','{% url 'shell:sshterminalmonitor' object.id %}');">Monitor</button>
                                                <button class="btn btn-xs btn-danger" type="button" onclick="kill('{{object.channel}}','{{object.user.username}}')">Kill</button>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static "js/json-view/jquery.jsonview.min.js" %}"></script>
    <script src="{% static "js/bootstrap-dialog/js/bootstrap-dialog.js" %}"></script>
    <script src="{% static "js/bootbox/bootbox.js" %}"></script>
    <script src="{% static "js/toastr/toastr.min.js" %}"></script>

<!--dynamic table-->
<script type="text/javascript" language="javascript" src="{% static "js/advanced-datatable/js/jquery.dataTables.js" %}"></script>
<script type="text/javascript" src="{% static "js/data-tables/DT_bootstrap.js" %}"></script>
<!--dynamic table initialization -->
<script src="{% static "js/dynamic_table_init.js" %}"></script>
    <script type="application/javascript">
    function play(user, ip, start_time, end_time, url){
        var div_username = ' user: '+'<span class="text-info">'+user+'' + '</span>';
        var div_ip = ' server: '+'<span class="text-info">' + ip + '</span>';
        var div_time = ' start time: ' + '<span class="text-info">'+start_time +'</span>' + ' end time: ' +'<span class="text-info">' + end_time + '</span>';
        var title = div_username + div_ip + div_time;
        BootstrapDialog.show({
            title: title,
            type: BootstrapDialog.TYPE_DEFAULT,
            message:$('<div style="overflow: auto;background-color: rgba(0, 0, 0, 0);"></div>').load(url)
        });
        return false;
    }

    function kill(channel_name,user_name) {
    var dialog = bootbox.confirm({
        title: "<a class='text-danger'>"+'kick user ' + user_name +" out </a>",
        message: 'Are you sure to kick user ' + user_name +' out ?',
        buttons: {
            confirm: {
                label: 'kill',
                className: 'btn-danger'
            },
            cancel: {
                label: 'cancel',
                className: 'btn-success'
            }
        },
        callback: function (result) {
            if (result){
                $.ajax({
                    type: "POST",
                    url: '{% url 'shell:sshterminalkill' %}',
                    dataType: "json",
                    data: {'channel_name': channel_name, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    success: function (data) {
                        if (data['status']){
                            toastr["success"](data['message']);
                            setTimeout(function () {
                                location.reload();
                            },2000);
                        }else{
                            toastr["error"](data['message']);
                        }
                    },
                    failure: function (errMsg) {
                        toastr["error"](errMsg);
                    }
                });
            }
        }
    });
}

function monitor(user,ip,start_time,url){
        var div_username = ' user: '+'<span class="text-info">'+user+'' + '</span>';
        var div_ip = ' server: '+'<span class="text-info">' + ip + '</span>';
        var div_time = ' start time: ' + '<span class="text-info">'+start_time +'</span>';
        var title = div_username + div_ip + div_time;
        BootstrapDialog.show({
            size: BootstrapDialog.SIZE_WIDE,
            title: title,
            type: BootstrapDialog.TYPE_DEFAULT,
            message:$('<div style="overflow: auto;background-color: rgba(0, 0, 0, 0);"></div>').load(url),
            draggable: true
        });
        return false;
    }
</script>
{% endblock %}

shell/templates/shell/server_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static "js/toastr/toastr.css" %}">
    <link rel="stylesheet" href="{% static 'js/xterm/xterm.css' %}"/>
    <link rel="stylesheet" href="{% static 'js/jstree/themes/proton/style.min.css' %}"/>
{#    <link rel="stylesheet" href="{% static 'fonts/css/font-awesome.min.css' %}"/>#}
{% endblock %}

{% block page-body %}
<div class="row">
    <div class="col-md-3">
        <div class="panel">
            <div class="panel-body">
                <form id="search">
                    <div class="input-group m-bot15">
                        <input id="q" type="search" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Search</button>
                        </span>
                    </div>
                </form>
                <div id="server_list" class="tree-demo" role="tree"></div>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <section class="panel">
            <header class="panel-heading custom-tab ">
                <ul class="nav nav-tabs" id="myTab">
                    <li class="active">
                        <a href="#help" data-toggle="tab">
                            Help
                            <button class="close closeTab" type="button" >&nbsp×&nbsp</button>
                        </a>
                    </li>
                </ul>
            </header>
            <div class="panel-body">
                <div class="tab-content">
                    <div class="tab-pane active" id="help">
                        Help info
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/xterm/xterm.js' %}"></script>
<script src="{% static 'js/xterm/addons/fit/fit.js' %}"></script>
<script src="{% static 'js/xterm/addons/terminado/terminado.js' %}"></script>
<script src="{% static 'js/xterm/addons/fullscreen/fullscreen.js' %}"></script>
<script src="{% static 'js/jstree/jstree.js' %}"></script>
<script src="{% static "js/toastr/toastr.min.js" %}"></script>

<script type="application/javascript">


    var currentTab;
    var composeCount = 0;
    //initilize tabs
    $(function () {

        //when ever any tab is clicked this method will be call
        $("#myTab").on("click", "a", function (e) {
            e.preventDefault();

            $(this).tab('show');
            $currentTab = $(this);
        });


        //registerComposeButtonEvent();
        registerCloseEvent();
    });


    //this method will register event on close icon on the tab..
    function registerCloseEvent() {
        $(".closeTab").click(function () {
            var tabContentId = $(this).parent().attr("href");
            $(this).parent().parent().remove(); //remove li of tab
            $('#myTab a:last').tab('show'); // Select first tab
            $.ajax({
                type: "POST",
                url: '{% url 'shell:sshterminalkill' %}',
                dataType: "json",
                data: {
                    'channel_name':$(tabContentId).attr('channel_name'),
                    'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function (data) {

                    if (data['status']){
                        toastr["success"](data['message']);
                    }
                },
                failure: function (errMsg) {
                    toastr["error"](errMsg);
                }
            });
            $(tabContentId).remove(); //remove respective tab content
        });
    }

    //shows the tab with passed content div id..paramter tabid indicates the div where the content resides
    function showTab(tabId) {
        $('#myTab a[href="#' + tabId + '"]').tab('show');
    }
    //return current active tab
    function getCurrentTab() {
        return currentTab;
    }


    //this will return element from current tab
    //example : if there are two tabs having  textarea with same id or same class name then when $("#someId") whill return both the text area from both tabs
    //to take care this situation we need get the element from current tab.
    function getElement(selector) {
        var tabContentId = $currentTab.attr("href");
        return $("" + tabContentId).find("" + selector);

    }


    function removeCurrentTab() {
        var tabContentId = $currentTab.attr("href");
        $currentTab.parent().remove(); //remove li of tab
        $('#myTab a:last').tab('show'); // Select first tab
        $(tabContentId).remove(); //remove respective tab content
    }

</script>
<script type="application/javascript">
    function make_terminal(element, size, ws_url,ip, key_pair, hostname) {
        var term = new Terminal({
            {#cols: size.cols,#}
            {#rows: size.rows,#}
            screenKeys: true,
            useStyle: true,
            cursorBlink: true  // Blink the terminal's cursor
        });
        term.open(element, false);
        var ws = new WebSocket(ws_url);
        ws.onopen = function (event) {
            term.resize(term.cols, term.rows);
            ws.send(JSON.stringify(["ip", ip, term.cols, term.rows, key_pair, hostname]));
            term.on('data', function (data) {
                ws.send(JSON.stringify(['stdin', data]));
            });

            ws.onmessage = function (event) {
                json_msg = JSON.parse(event.data);
                switch (json_msg[0]) {
                    case "stdout":
                        term.write(json_msg[1]);
                        break;
                    case "disconnect":
                        term.write("\r\n\r\n[Finished...]\r\n");
                        break;
                    case "channel_name":
                        var channel_name_attribute = document.createAttribute('channel_name');
                        channel_name_attribute.value = json_msg[1];
                        element.setAttributeNode(channel_name_attribute);
                        break;
                }
            };
        };
        return {socket: ws, term: term};
    }

    //make_terminal(document.getElementById('terminal-container1'), {rows: 40, cols: 90}, ws_path);
//    var term = new Terminal({
//        cols: 90,
//        rows: 40,
//        screenKeys: true,
//        useStyle: true,
//        cursorBlink: true,  // Blink the terminal's cursor
//    });
//    term.open(document.getElementById('terminal-container1'), false);
//    term.write('\033[1;3;31mThis is the webterminal console Please select a server to connect!\033[0m')
</script>
<script type="application/javascript">
    $("#server_list").jstree({
        core: {
            'themes': {
                'name': 'proton',
                'responsive': true
            },
            check_callback: !0,
            data: {
                url: '/shell/{{ region }}/{{ role }}/js',
                type: 'GET'
            },
            load_open : true
        },
        types: {
            "default": {icon: "fa fa-folder icon-state-warning icon-lg"},
            file: {icon: "fa fa-file icon-state-warning icon-lg"}
        },
        state: {key: "demo2"},
        plugins: ["contextmenu", "state", "types", "search", "json_data"],
        contextmenu: {
            "items": function ($node) {
                var tree = $("#server_list").jstree(true);
                return {
                    "connect": {
                        "separator_before": false,
                        "separator_after": false,
                        "label": "connect",
                        "action": function (obj) {
                            var tabId_org = $node.original.hostname;
                            //get server ip

                            var ip = $node.original.ip;
                            var key_pair = $node.original.key_pair;
                            var tab_count = 0;
                            var tabId = tabId_org + '-' + tab_count;
                            while (true){
                                if ($('#' + tabId).length <= 0){
                                    break
                                } else {
                                    tab_count++;
                                    tabId = tabId_org + '-' + tab_count;
                                }
                            }
                            $('.nav-tabs').append('<li><a href="#' + tabId + '"><button class="close closeTab" type="button" > × </button>' + tabId + '</a></li>');
                            $('.tab-content').append('<div class="tab-pane" id="' + tabId + '"></div>');
                            showTab(tabId);
                            registerCloseEvent();
                            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
                            var ws_path = ws_scheme + '://' + window.location.host + '/ws/';
                            make_terminal(document.getElementById(tabId), {rows: 20, cols: 80}, ws_path, ip, key_pair, $node.original.hostname);
                        }
                    }
                };
            }
        }
    }).on('show_contextmenu.jstree', function(e, reference, element) {
        if ( reference.node.parents.length < 2 ) {
            $('.vakata-context').remove();
        }
    });
    $("#search").submit(function(e) {
        e.preventDefault();
        $("#server_list").jstree(true).search($("#q").val());
    });
</script>

{% endblock %}