account/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from views import LoginView, Profile, LogoutView

from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile/$', Profile.as_view(), name='profile')
]

ops_shell/urls.py
from django.conf.urls import url, include
from django.contrib import admin

#Webterminal api
from rest_framework import routers
from shell.api import ServerGroupViewSet,ServerInforViewSet,CommandsSequenceViewSet,CredentialViewSet

from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.views.static import serve

#Register webterminal api
router = routers.DefaultRouter()
router.register('servergroup', ServerGroupViewSet)
router.register('serverinfo', ServerInforViewSet)
router.register('commandssequence', CommandsSequenceViewSet)
router.register('credential', CredentialViewSet)

from shell import urls as shell_urls
from account import urls as account_urls

from settings import MEDIA_ROOT

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('shell:index')), name='index'),
    url(r'^shell/', include(shell_urls, namespace='shell')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
]

shell/urls.py
from django.conf.urls import url

from shell.views import IndexView
from shell.views import ServerListView, SshTerminalKill, server_list_js
from shell.views import SshLogList, SshTerminalMonitor, SshLogPlay

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^sshlogslist/$', SshLogList.as_view(), name='sshlogslist'),
    url(r'^sshterminalkill/$',SshTerminalKill.as_view(), name='sshterminalkill'),
    url(r'^sshlogplay/(?P<pk>[0-9]+)/', SshLogPlay.as_view(), name='sshlogplay'),
    url(r'^sshterminalmonitor/(?P<pk>[0-9]+)/', SshTerminalMonitor.as_view(), name='sshterminalmonitor'),
    url(r'^(?P<region>[\w-]+)/(?P<role>[\w-]+)/$', ServerListView.as_view(), name='server_list'),
    url(r'^(?P<region>[\w-]+)/(?P<role>[\w-]+)/js/$', server_list_js, name='server_list_js'),



]

templates/base.html
{% load staticfiles %}

{% load sidebar %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="keywords" content="admin, dashboard, bootstrap, template, flat, modern, theme, responsive, fluid, retina, backend, html5, css, css3">
  <meta name="description" content="">
  <meta name="author" content="ThemeBucket">
  <link rel="shortcut icon" href="#" type="image/png">

  <title>
      {% block title %}
          DEVOPS Shell
      {% endblock %}
  </title>

  <!--common-->

  <link href="{% static "css/style.css" %}" rel="stylesheet">
  <link href="{% static "css/style-responsive.css" %}" rel="stylesheet">
  {% block css %}
  {% endblock %}

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
  <![endif]-->
</head>

<body class="sticky-header">

<section>
    <!-- left side start-->
    <div class="left-side sticky-left-side">

        <!--logo and iconic logo start-->
        <div class="logo">
            <a href={% url "shell:index" %}><img src="{% static "images/logo.png" %}" alt=""></a>
        </div>

        <div class="logo-icon text-center">
            <a href={% url "shell:index" %}><img src="{% static "images/logo_icon.png" %}" alt=""></a>
        </div>
        <!--logo and iconic logo end-->

        <div class="left-side-inner">
            {% render_sidebar %}
        </div>
    </div>
    <!-- left side end-->

    <!-- main content start-->
    <div class="main-content" >

        <!-- header section start-->
        {% include 'header.html' %}
        <!-- header section end-->

        {% block page-header %}

        {% endblock %}

        <!--body wrapper start-->
        <div class="wrapper">
            {% block page-body %}
            {% endblock %}
        </div>
        <!--body wrapper end-->
        <footer>
            2014 &copy; AdminEx by ThemeBucket
    </footer>
    </div>
    <!-- main content end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
<script src="{% static "js/jquery-1.10.2.min.js" %}"></script>
{#<script src="{% static "js/jquery-ui-1.9.2.custom.min.js" %}"></script>#}
<script src="{% static "js/jquery-ui-1.10.3.min.js" %}"></script>
<script src="{% static "js/jquery-migrate-1.2.1.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/modernizr.min.js" %}"></script>
<script src="{% static "js/jquery.nicescroll.js" %}"></script>

<!--common scripts for all pages-->
<script src="{% static "js/scripts.js" %}"></script>


{% block js %}
{% endblock %}
</body>
</html>

templates/header.html
{% load staticfiles %}

<div class="header-section">
    <!--toggle button start-->
    <a class="toggle-btn"><i class="fa fa-bars"></i></a>
    <!--toggle button end-->

    <!--notification menu start -->
    <div class="menu-right">
        <ul class="notification-menu">
            {% if user.is_authenticated %}
                <li>
                    <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <img src="/media/{{ user.user_profile.avatar }}" alt="" />
                        {{ user.username }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-usermenu pull-right">
                        <li><a href="{% url 'account:profile' %}"><i class="fa fa-user"></i> 个人信息</a></li>
                        <li><a href="{% url 'account:logout' %}"><i class="fa fa-sign-out"></i> 注销</a></li>
                    </ul>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'account:login' %}" class="btn btn-default dropdown-toggle info-number">
                        登录
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
    <!--notification menu end -->
</div>

templates/sidebar.html
{% load staticfiles %}

<ul class="nav nav-pills nav-stacked custom-nav">
    {% for region in regions %}
        <li class="menu-list {% if region.name in request.path %}active{% endif %}"><a href=""><i class="fa fa-laptop"></i> <span>{{ region.aws_name }}</span></a>
            <ul class="sub-menu-list">
                {% for role in region.roles.all %}
                    {% with region.name|add:'/'|add:role.name as current_path%}
                    <li class="{% if current_path in request.path %}active{% endif %}"><a href={% url "shell:server_list" region=region.name role=role.name %}>{{ role.name }}</a></li>
                    {% endwith %}
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    {% if user.user_profile.role == 'Admin'%}
        <li><a href={% url 'shell:sshlogslist' %}>Logs</a></li>
    {% endif %}
</ul>